version: "3"
services:
#  frontend:
#    build:
#      context: docker/development/nginx-front
#    ports:
#      - "8080:80"
#    volumes:
#      - ./frontend:/app
#    networks:
#      - eshop-network

  frontend-nodejs:
    image: node:14.17-alpine
    volumes:
      - ./front:/app
    working_dir: /app
    tty: true
    networks:
      - eshop-network

  front:
    build:
      context: docker/development/nginx-front
    ports:
      - "8080:80"
    volumes:
      - ./front:/app
    networks:
      - eshop-network

  api:
    build:
      context: docker/development/nginx-api
    ports:
      - "8081:80"
    volumes:
      - ./api:/app
    depends_on:
      - php-fpm-api
    networks:
      - eshop-network

  php-fpm-api:
    build:
      context: docker/development/php-fpm-api
    volumes:
      - ./:/app
    extra_hosts:
      - "localhost:172.22.17.1"
      - "host.docker.internal:172.22.17.1"
    environment:
      XDEBUG_CONFIG: "remote_host=172.22.17.1 remote_enable=1 discover_client_host=1"
      PHP_ENABLE_XDEBUG: 1
      PHP_IDE_CONFIG: "serverName=PhpServerBase"
    networks:
      - eshop-network

  mysql:
    build: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=verysecret
    volumes:
      - "./mysql/database:/var/lib/mysql"
    ports:
      - '3306:3306'
    networks:
      - eshop-network

networks:
  eshop-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.17.0/16