version: '3.2'

services:

  frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    extra_hosts:
      - "localhost:172.22.17.1"
      - "host.docker.internal:172.22.17.1"
    environment:
        XDEBUG_CONFIG: "remote_host=172.22.17.1 remote_enable=1 discover_client_host=1"
     # - PHP_ENABLE_XDEBUG=1
        PHP_ENABLE_XDEBUG: 1
        PHP_IDE_CONFIG: "serverName=PhpServerBase"
    networks:
      - eshop-network

  api:
    build: api
    ports:
      - 22080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    extra_hosts:
      - "localhost:172.22.17.1"
      - "host.docker.internal:172.22.17.1"
    environment:
      XDEBUG_CONFIG: "remote_host=172.22.17.1 remote_enable=1 discover_client_host=1"
      # - PHP_ENABLE_XDEBUG=1
      PHP_ENABLE_XDEBUG: 1
      PHP_IDE_CONFIG: "serverName=PhpServerBase"
    networks:
      - eshop-network

  backend:
    build: backend
    ports:
      - 21080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    networks:
      - eshop-network

  mysql:
    build: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=verysecret
    volumes:
      - "./mysql/database:/var/lib/mysql"
    ports:
      - '3306:3306'
    networks:
      - eshop-network

#  pgsql:
#    image: postgres:13
#    environment:
#      - POSTGRES_DB=yii2advanced
#      - POSTGRES_USER=yii2advanced
#      - POSTGRES_PASSWORD=secret

networks:
  eshop-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.17.0/16